# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: lnenita <lnenita@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2019/04/22 18:30:30 by lnenita           #+#    #+#              #
#    Updated: 2019/04/24 12:13:54 by lnenita          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file
FILE = *.c

all:
	gcc $(FILE) -o $(NAME)

clean:
	/bin/rm -f *.o

fclean: clean
	/bin/rm -f $(NAME)

re: fclean re
